# TCL File Generated by Component Editor 9.1sp2
# Mon Jul 26 13:33:06 CST 2010
# DO NOT MODIFY


# +-----------------------------------
# | 
# | TERASIC_D5M "TERASIC_D5M" v1.0
# | null 2010.07.26.13:33:06
# | 
# | 
# | D:/svn/tPAD/tPAD_VIP_CAMERA/ip/TERASIC_D5M/TERASIC_D5M.v
# | 
# |    ./TERASIC_D5M.v syn, sim
# |    ./D5M_RGB.v syn, sim
# |    ./D5M_Bayer.v syn, sim
# |    ./Bayer2RGB.v syn, sim
# |    ./Bayer_LineBuffer.v syn, sim
# |    ./rgb_fifo.v syn, sim
# | 
# +-----------------------------------

# +-----------------------------------
# | request TCL package from ACDS 9.1
# | 
package require -exact sopc 9.1
# | 
# +-----------------------------------

# +-----------------------------------
# | module TERASIC_D5M
# | 
set_module_property NAME TERASIC_D5M
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property GROUP "Terasic Technologies Inc"
set_module_property DISPLAY_NAME TERASIC_D5M
set_module_property TOP_LEVEL_HDL_FILE TERASIC_D5M.v
set_module_property TOP_LEVEL_HDL_MODULE TERASIC_D5M
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL TRUE
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file TERASIC_D5M.v {SYNTHESIS SIMULATION}
add_file D5M_RGB.v {SYNTHESIS SIMULATION}
add_file D5M_Bayer.v {SYNTHESIS SIMULATION}
add_file Bayer2RGB.v {SYNTHESIS SIMULATION}
add_file Bayer_LineBuffer.v {SYNTHESIS SIMULATION}
add_file rgb_fifo.v {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | display items
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clock_reset
# | 
add_interface clock_reset clock end

set_interface_property clock_reset ENABLED true

add_interface_port clock_reset clk clk Input 1
add_interface_port clock_reset reset_n reset_n Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point conduit_end
# | 
add_interface conduit_end conduit end

set_interface_property conduit_end ASSOCIATED_CLOCK clock_reset
set_interface_property conduit_end ENABLED true

add_interface_port conduit_end D5M_D export Input 12
add_interface_port conduit_end D5M_FVAL export Input 1
add_interface_port conduit_end D5M_LVAL export Input 1
add_interface_port conduit_end D5M_PIXLCLK export Input 1
add_interface_port conduit_end D5M_SCLK export Output 1
add_interface_port conduit_end D5M_SDATA export Bidir 1
add_interface_port conduit_end D5M_STROBE export Input 1
add_interface_port conduit_end D5M_TRIGGER export Output 1
add_interface_port conduit_end D5M_XCLKIN export Output 1
add_interface_port conduit_end D5M_RESET_N export Output 1
add_interface_port conduit_end INFO_FRAME_COUNT export Output 22
add_interface_port conduit_end INFO_FRAME_START export Output 1
add_interface_port conduit_end INFO_FRAME_END export Output 1
add_interface_port conduit_end INFO_FRAME_PIX_COUNT export Output 22
add_interface_port conduit_end USER_CTRL export Input 1
add_interface_port conduit_end INFO_FRAME_INVALID_COUNT export Output 22
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point avalon_streaming_source
# | 
add_interface avalon_streaming_source avalon_streaming start
set_interface_property avalon_streaming_source associatedClock clock_reset
set_interface_property avalon_streaming_source dataBitsPerSymbol 8
set_interface_property avalon_streaming_source errorDescriptor ""
set_interface_property avalon_streaming_source maxChannel 0
set_interface_property avalon_streaming_source readyLatency 0

set_interface_property avalon_streaming_source ASSOCIATED_CLOCK clock_reset
set_interface_property avalon_streaming_source ENABLED true

add_interface_port avalon_streaming_source st_data data Output 24
add_interface_port avalon_streaming_source st_sop startofpacket Output 1
add_interface_port avalon_streaming_source st_eop endofpacket Output 1
add_interface_port avalon_streaming_source st_ready ready Input 1
add_interface_port avalon_streaming_source st_valid valid Output 1
# | 
# +-----------------------------------
